<a href="https://colab.research.google.com/github/Abishethvarman/100-days-of-code/blob/main/TF_1_TF2_Quick_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.12472609, -0.0651876 , -0.4502827 ,  0.02500404,  0.24233884,
         0.01349425, -0.39772156, -0.36231518, -0.18720546,  0.14216568]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.12089718, 0.09998565, 0.06802883, 0.10942269, 0.13598616,
        0.10817049, 0.07170014, 0.07428426, 0.08850056, 0.12302406]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.2240467

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2931 - accuracy: 0.9155
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1397 - accuracy: 0.9586
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1052 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0871 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0711 - accuracy: 0.9777


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0680 - accuracy: 0.9798 - 554ms/epoch - 2ms/step


[0.06800562888383865, 0.9797999858856201]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.5807600e-08, 1.4582405e-08, 9.1735365e-06, 3.0957792e-05,
        2.7684060e-11, 1.3869484e-07, 7.8008731e-13, 9.9995911e-01,
        1.2975755e-07, 2.9242318e-07],
       [3.4763828e-10, 1.9051533e-04, 9.9979681e-01, 5.2577667e-07,
        3.3842143e-17, 1.2087882e-05, 7.2145070e-08, 7.3883999e-15,
        1.6796209e-09, 5.4831655e-14],
       [1.5572613e-07, 9.9945289e-01, 6.7486100e-05, 9.2155682e-07,
        2.8740955e-05, 2.8996746e-07, 7.9018409e-06, 4.2405224e-04,
        1.7479248e-05, 2.0148327e-07],
       [9.9931049e-01, 6.4986185e-09, 4.0225402e-04, 4.4002687e-07,
        6.2554989e-07, 4.3474806e-06, 8.4081468e-05, 1.2759629e-05,
        4.9663442e-09, 1.8508060e-04],
       [1.2650171e-06, 3.8564044e-10, 1.1189211e-06, 1.1868332e-08,
        9.9659675e-01, 1.5589809e-07, 1.0347732e-05, 4.6620316e-05,
        4.5373841e-07, 3.3431954e-03]], dtype=float32)>